name: C1 Clean Build

on:
  push:
    paths: [ linux ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: download
      shell: bash
      run: wget https://github.com/YuYeolLee/linux/archive/$(git rev-parse HEAD:./linux).zip

    - name: unzip
      shell: bash
      run: unzip $(git rev-parse HEAD:./linux).zip

    - name: clean build
      shell: bash
      run: ./build-linux.sh linux-$(git rev-parse HEAD:./linux) tinyconfig
