name: C2 clean compilation

on:
  push:
    path:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: make -C test
