name: C2 clean compilation

on:
  push:
    paths:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
        uses: actions/checkout@v2

      - name: test
        shell: bash
        run: make -C test
